sudo: required
services: 
  - docker
before_install:
  - docker build -t rpetermeier/docker-react -f Dockerfile.dev .
script:
  - docker run rpetermeier/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker-react"
    env: "Docker-react-env"
    bucket_name: "TODO"
    bucket_path: "TODO"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"